config/routes.rb
OpenSensor::Application.routes.draw do
  resources :flows
  resources :flow_power_daily_sum, controller: 'flows', type: 'Flow' 
  resources :flow_avg,             controller: 'flows', type: 'Flow' 


  resources :elements


  resources :actions


  get "welcome/index"

  resources :twitter_credentials do
   collection do
      get 'connect'
      get 'callback'
    end
  end


  resources :element_prototypes


  resources :sensors do
    member do
      delete 'drop'
    end
  end

  resources :triggers


  resources :widgets

  resources :home

  resources :dashboards do
    member do
      post 'positions'
    end
   collection do
      get 'subscribe'
      post 'webhook'
    end
  end
  
  resources :measures


  resources :feeds do
    member do
      get 'graph'
    end
  end

  resources :devices

  authenticated :user do
    root :to => 'users#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users



end

app/models/feed.rb
class Feed < Sensor

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = current_user.feeds

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  def graph
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new
    if params[:device]
      device=Device.find params[:device]
      @feed.device=device
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(params[:feed])
    @feed.user=@current_user
    
    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :device %><br />
    <%= f.select(:device_id,options_for_select(@current_user.devices.map{|d|[d.name,d.id]},:selected => @feed.device_id)) %>
  </div>
    <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
    <div class="field">
    <%= f.label :type %><br />
    <%= f.select(:type,options_for_select(%w(Float Int Binary String),:selected => @feed.type)) %>
  </div>  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/graph.html.erb
<p id="notice"><%= notice %></p>
<link href="/assets/nv.d3.css" rel="stylesheet">
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="/assets/nv.d3.js"></script>
<script>
nv.addGraph(function() {
  var chart = nv.models.lineWithFocusChart();

  chart.xAxis
      .tickFormat(d3.format(',f'));

  chart.yAxis
      .tickFormat(d3.format(',.2f'));

  chart.y2Axis
      .tickFormat(d3.format(',.2f'));

  d3.select('#chart svg')
      .datum(testData())
      .transition().duration(500)
      .call(chart);

  nv.utils.windowResize(chart.update);

  return chart;
});
/**************************************
 * Simple test data generator
 */

function testData() {
  return stream_layers(3,128,.1).map(function(data, i) {
    return { 
      key: 'Stream' + i,
      values: data
    };
  });
}

</script>
<div id="chart"> <svg style='height:500px'> </svg></div>
<p>
  <b>Name:</b>
  <%= @feed.name %>
</p>

<p>
  <b>Description:</b>
  <%= @feed.description %><br>
  <%= "Total:#{@feed.measures.count}" %><br/>
  <% if @feed.last_measure %>
  <%= "Last:#{@feed.last_measure.value}" %>
  <% end %>
</p>

<p>
  <b>Attached on device:</b>
  <%= link_to @feed.device.name,device_path(@feed.device) %>
</p>
<p>
</p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Your Feeds</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Type</th>
    <th>Unit</th>
    <th>Measures</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.name %></td>
    <td><%= feed.description %></td>
    <td><%= feed.type %></td>
    <td><%= feed.unit %></td>
    <td><%= feed.measures.count %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path,:class=>"btn btn-primary" %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>


<p>
  <b>Name:</b>
  <%= @feed.name %>
</p>
<p>
  <b>Unit:</b>
  <%= @feed.unit %>
</p>
<p>
  <b>Type:</b>
  <%= @feed.type %>
</p>

<p>
  <b>Description:</b>
  <%= @feed.description %><br>
  <%= "Total:#{@feed.measures.count}" %><br/>
  <% if @feed.last_measure %>
  <%= "Last:#{@feed.last_measure.value}" %>
  <% end %>
</p>

<p>
  <b>Attached on device:</b>
  <%= link_to @feed.device.name,device_path(@feed.device) %>
</p>
<p>
</p>
<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>