config/routes.rb
OpenSensor::Application.routes.draw do
  resources :flows
  resources :flow_power_daily_sum, controller: 'flows', type: 'Flow' 
  resources :flow_avg,             controller: 'flows', type: 'Flow' 


  resources :elements


  resources :actions


  get "welcome/index"

  resources :twitter_credentials do
   collection do
      get 'connect'
      get 'callback'
    end
  end


  resources :element_prototypes


  resources :sensors do
    member do
      delete 'drop'
    end
  end

  resources :triggers


  resources :widgets

  resources :home

  resources :dashboards do
    member do
      post 'positions'
    end
   collection do
      get 'subscribe'
      post 'webhook'
    end
  end
  
  resources :measures


  resources :feeds do
    member do
      get 'graph'
    end
  end

  resources :devices

  authenticated :user do
    root :to => 'users#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users



end

app/models/twitter_credential.rb
class TwitterCredential
  include Mongoid::Document
  field :screen_name, type: String
  field :twitter_id, type: String
  field :token_access, type: String
  field :token_secret, type: String
  belongs_to :user

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key = TWITTER_CONSUMER_KEY
      config.consumer_secret = TWITTER_CONSUMER_SECRET
      config.access_token = self.token_access
      config.access_token_secret = self.token_secret
    end
  end

  def update message
    self.client.update(message)
  end

  def send_dm user, message
    self.client.create_direct_message(user, message)
  end
end

app/controllers/twitter_credentials_controller.rb
class TwitterCredentialsController < ApplicationController
  before_filter :authenticate_user!

  def connect
    puts "In connect"

    session[:twitter_referer]=request.env["HTTP_REFERER"]
    puts "Source:"+session[:twitter_referer].to_s

    client =TwitterOAuth::Client.new(
        :consumer_secret => TWITTER_CONSUMER_SECRET,
        :consumer_key => TWITTER_CONSUMER_KEY)
    puts client.inspect
    puts "Callback: http://#{request.env['SERVER_NAME']}:#{request.env['SERVER_PORT']}/twitter_credentials/callback"
    requestOauth= client.request_token(:oauth_callback => "http://#{request.env['SERVER_NAME']}:#{request.env['SERVER_PORT']}/twitter_credentials/callback")
    session[:token]=requestOauth.token
    session[:secret]=requestOauth.secret
    redirect_to requestOauth.authorize_url
  end

  def callback
    begin
      if params[:denied]
        flash[:notice]="No problem, you will be able to log in anytime"
        redirect_to "/"
      else
        puts params.to_s
        client =TwitterOAuth::Client.new(
            :consumer_secret => TWITTER_CONSUMER_SECRET,
            :consumer_key => TWITTER_CONSUMER_SECRET)
        access_token = client.authorize(
            session[:token],
            session[:secret],
            :oauth_verifier => params[:oauth_verifier]

        )
        puts access_token.inspect
        puts "screen name"+access_token.params[:screen_name]
        cred=TwitterCredential.where(:user => @current_user, :twitter_id => access_token.params[:user_id].to_s).first
        if cred==nil
          cred=TwitterCredential.where(:user => @current_user, :screen_name => access_token.params[:screen_name]).first
        end
        if cred==nil
          cred=TwitterCredential.new(:user => @current_user)
        end
        cred.twitter_id=access_token.params[:user_id]
        cred.screen_name=access_token.params[:screen_name]
        cred.token_access=access_token.token
        cred.token_secret=access_token.secret
        cred.save
        redirect=session[:twitter_referer]
        session[:twitter_referer]=nil
        # If there is a current trigger being creaed

        if session[:trigger]
          trigger=Trigger.find session[:trigger]
          if trigger.target!=cred.screen_name
            trigger.target=cred.screen_name
            trigger.save
            session[:trigger]=nil
            flash.notice="Warning,you've registered with a different twitter account, this will be updated"
          end

        end

        # Do a test
        puts "Authorized: #{client.authorized?}"
        # if  !client.authorized?
        #   flash[:notice]="error authorization"
        # end
        if redirect then
          redirect_to redirect
        else
          redirect_to :action => "show"
        end
      end
    rescue Exception => e
      flash.notice="error while getting authorization"
      redirect_to "/"
    end
  end

  # GET /twitter_credentials
  # GET /twitter_credentials.json
  def index
    @twitter_credentials = TwitterCredential.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @twitter_credentials }
    end
  end

  # GET /twitter_credentials/1
  # GET /twitter_credentials/1.json
  def show
    @twitter_credential = TwitterCredential.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @twitter_credential }
    end
  end

  # GET /twitter_credentials/new
  # GET /twitter_credentials/new.json
  def new
    @twitter_credential = TwitterCredential.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @twitter_credential }
    end
  end

  # GET /twitter_credentials/1/edit
  def edit
    @twitter_credential = TwitterCredential.find(params[:id])
  end

  # POST /twitter_credentials
  # POST /twitter_credentials.json
  def create
    @twitter_credential = TwitterCredential.new(params[:twitter_credential])

    respond_to do |format|
      if @twitter_credential.save
        format.html { redirect_to @twitter_credential, notice: 'Twitter credential was successfully created.' }
        format.json { render json: @twitter_credential, status: :created, location: @twitter_credential }
      else
        format.html { render action: "new" }
        format.json { render json: @twitter_credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /twitter_credentials/1
  # PUT /twitter_credentials/1.json
  def update
    @twitter_credential = TwitterCredential.find(params[:id])

    respond_to do |format|
      if @twitter_credential.update_attributes(params[:twitter_credential])
        format.html { redirect_to @twitter_credential, notice: 'Twitter credential was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @twitter_credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitter_credentials/1
  # DELETE /twitter_credentials/1.json
  def destroy
    @twitter_credential = TwitterCredential.find(params[:id])
    @twitter_credential.destroy

    respond_to do |format|
      format.html { redirect_to twitter_credentials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/twitter_credentials_helper.rb
module TwitterCredentialsHelper
end

app/views/twitter_credentials/_form.html.erb
<%= form_for(@twitter_credential) do |f| %>
  <% if @twitter_credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_credential.errors.count, "error") %> prohibited this twitter_credential from being saved:</h2>

      <ul>
      <% @twitter_credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_credentials/edit.html.erb
<h1>Editing twitter_credential</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_credential %> |
<%= link_to 'Back', twitter_credentials_path %>

app/views/twitter_credentials/index.html.erb
<h1>Listing twitter_credentials</h1>

<table>
  <tr>
    <th>Screen name</th>
    <th>Token</th>
    <th>Token secret</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @twitter_credentials.each do |twitter_credential| %>
  <tr>
    <td><%= twitter_credential.screen_name %></td>
    <td><%= link_to 'Show', twitter_credential %></td>
    <td><%= link_to 'Edit', edit_twitter_credential_path(twitter_credential) %></td>
    <td><%= link_to 'Destroy', twitter_credential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Twitter credential', new_twitter_credential_path %>

app/views/twitter_credentials/new.html.erb
<h1>New twitter_credential</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_credentials_path %>

app/views/twitter_credentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Screen name:</b>
  <%= @twitter_credential.screen_name %>
</p>

<p>
  <b>Token:</b>
  <%= @twitter_credential.token_access %>
</p>

<%= link_to 'Edit', edit_twitter_credential_path(@twitter_credential) %> |
<%= link_to 'Back', twitter_credentials_path %>