config/routes.rb
OpenSensor::Application.routes.draw do
  resources :flows
  resources :flow_power_daily_sum, controller: 'flows', type: 'Flow' 
  resources :flow_avg,             controller: 'flows', type: 'Flow' 


  resources :elements


  resources :actions


  get "welcome/index"

  resources :twitter_credentials do
   collection do
      get 'connect'
      get 'callback'
    end
  end


  resources :element_prototypes


  resources :sensors do
    member do
      delete 'drop'
    end
  end

  resources :triggers


  resources :widgets

  resources :home

  resources :dashboards do
    member do
      post 'positions'
    end
   collection do
      get 'subscribe'
      post 'webhook'
    end
  end
  
  resources :measures


  resources :feeds do
    member do
      get 'graph'
    end
  end

  resources :devices

  authenticated :user do
    root :to => 'users#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users



end

app/models/sensor.rb
class Sensor
  include Mongoid::Document

  field :name, type: String
  field :description, type: String
  field :type, type: String, :default => "Float"
  field :unit, type: String, :default => ""
  field :is_saved, type: Boolean, :default => true

  # Last value, used manyly when feed is notsaved
  field :last_measure, type: Hash

  belongs_to :device
  has_many :measures # only is is_saved==true
  has_and_belongs_to_many :elements
  belongs_to :user
  before_destroy :delete_measures

  index({devices: 1}, {background: true})

  Pusher.url = "http://#{PUSHER_KEY}:#{PUSHER_SECRET}@api.pusherapp.com/apps/#{PUSHER_APP}"

  def Sensor.find_by_name_or_create name, device
    sensor = Sensor.where(:device => device, :name => name).first
    if sensor == nil
      puts "Creating sensor:#{name}"
      sensor=Sensor.new(:name => name)
      sensor.device=device
      sensor.user=device.user
      sensor.save
    else
      puts "sensor found"
    end
    sensor
  end

  def Sensor.sensor_types
    %w(Float Int Boolean String Position)
  end

  def Sensor.check_and_update sensors
=begin
    puts "in check and pudate"
    sensors.each{|s| s.publish}
    dashboards={}
    puts "after sensors Size:#{sensors.size}"
    puts "Sensor:#{sensors}"
    sensors.each do |sensor|
      sensor.actions.where(:_type=>Widget).each do |widget|
        puts "Widget #{widget.name} in dashboard:#{widget.dashboard.name}"
        to_send={:_id=>widget.id,:data=>widget.sensor.last_measure.as_json}
        dashboards[widget.dashboard]=(dashboards[widget.dashboard]||[])+[to_send]
      end
    end

    puts dashboards
    dashboards.each do |dashboard,widgets|
      publish_on dashboard,widgets 
    end
=end


  end

  def publish(force_publish=false)
    if self[:active_channel]==true ||force_publish
      puts "Published:#{self.name} #{self.last_measure}"
      Pusher["sensor-#{self.id}"].trigger('update', self.last_measure.to_json)
    else
      puts "Channel:#{self.name} inactive"
    end
  end

  def Sensor.publish_on dashboard, content

    if dashboard.active_channel?
      puts "Published:#{dashboard.name} #{content}"
      Pusher["dashboard-#{dashboard.id}"].trigger('update', content)
    else
      puts "Channel:#{dashboard.name} inactive"
    end
  end


  #  def last_measure
  #  	self.measures.desc(:timeStamp).first||Measure.new(:value=>"N/A")
  #  end
  def device= in_device
    self[:device_id] = in_device.id
    self.user = in_device.user
  end

  def delete_measures
    self.measures.delete_all
  end

  def publish_update measure

    publish
    dashboards={}

    self.elements.where(:_type => Widget).each do |widget|
      puts "Widget #{widget.name} in dashboard:#{widget.dashboard.name}"
      to_send = {:_id => widget.id, :data => measure.as_json}
      dashboards[widget.dashboard]=(dashboards[widget.dashboard]||[])+[to_send]
    end

    dashboards.each do |dashboard, widgets|
      Sensor.publish_on dashboard, widgets
    end

  end

  def last_measure
    res = self[:last_measure]
    if res == nil
      res = {:value => "N/A", :timeStamp => Time.now}
    end
    return Measure.new(:sensor => self,
                       :value => res["value"],
                       :timeStamp => res["timeStamp"])
  end

  def add_measure value, timeStamp=Time.now
    m=Measure.new(:sensor => self, :value => value, :timeStamp => timeStamp)
    puts m

    if is_saved
      m.save
    end

    self.set(:last_measure, {"timeStamp" => m.timeStamp, "value" => m.value})
    publish_update m

    # Update all elemet execpt those which are output
    elements.each do |t|
      if !t.output_feed.include?(self)
        t.measure_added self, m
      end
    end

    return m
  end


end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_filter :authenticate_user!
  # GET /sensors
  # GET /sensors.json
  def index
    @sensors =  @current_user.sensors

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensors }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])
    if @sensor.user!=@current_user then raise "Sensor does not belongs to you"; end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sensor }
    end
  end

  def drop
    @sensor = Sensor.find(params[:id])
    if @sensor.user!=@current_user then raise "Sensor does not belongs to you"; end
    @sensor.measures.delete_all
    redirect_to @sensor

  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new
    if params[:device]
      device=Device.find params[:device]
      @sensor.device=device
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])
    if @sensor.user!=current_user then raise "Sensor does not belongs to you"; end
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])
    @sensor.user=@current_user
    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])
    if @sensor.user!=@current_user then raise "Sensor does not belongs to you"; end

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])
    if @sensor.user!=@current_user then raise "Sensor does not belongs to you"; end
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
  <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :device %><br />
    <%= f.select(:device_id,options_for_select(@current_user.devices.map{|d|[d.name,d.id]},:selected => @sensor.device_id)) %>
  </div>
    <div class="field">
    <%= f.label :type %><br />
    <%= f.select(:type,options_for_select(Sensor.sensor_types,:selected => @sensor.type)) %>
  </div> 
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing sensor</h1>

<%= render 'form' %>

app/views/sensors/index.html.erb
<h1>Listing sensors</h1>

A sensor is a feed of data provided by a device connected to the internet. Can be forinstance your Ardunio device . You can use the API to connect devices to OpenSensorCloud.
<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Type</th>
    <th>Unit</th>
    <th>Measures</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sensors.each do |sensor| %>
  <tr>
    <td><%= link_to sensor.name,sensor %></td>
    <td><%= sensor.description %></td>
    <td><%= sensor.type %></td>
    <td><%= sensor.unit %></td>
    <td><%= sensor.measures.count %> measures</td>
    <td><%= link_to 'Show', sensor %></td>
    <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
    <td><%= link_to 'Destroy', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sensor', new_sensor_path ,:class=>"btn btn-primary"%>

app/views/sensors/new.html.erb
<h1>New sensor</h1>

<%= render 'form' %>

<%= link_to 'Back', sensors_path %>

app/views/sensors/show.html.erb
<script src="http://code.highcharts.com/stock/highstock.js"></script>
<script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLFKOt7Y2ggj_6P_lNH8BOp_WmZ84K1Jc&sensor=SET_TO_TRUE_OR_FALSE" >
    </script>
<script type="text/javascript">
Highcharts.setOptions({ global: {timezoneOffset:(new Date()).getTimezoneOffset() ,useUTC: true}});

// Pusher
Pusher.log = function(message) {
  if (window.console && window.console.log) {
            window.console.log(message);
  }
};
<% use_presence=false %>
var prefix="<%= if use_presence then "presence-" else "" end %>";
var pusher = new Pusher(prefix+'<%= PUSHER_KEY -%>', { authEndpoint: '/dashboard/auth' });
var channel = pusher.subscribe('<%= "sensor-#{@sensor.id}" -%>');
channel.bind('update', function(data) {
  updateDatas(data);
});

</script>
<p id="notice"><%= notice %></p>

  <b>Name:</b>
  <%= @sensor.name %>
<%= link_to 'Edit', edit_sensor_path(@sensor),:class=>"btn" %>
 <%= link_to 'Remove all datas', drop_sensor_path(@sensor), method: :delete,:class=>"btn", data: { confirm: 'Delete all measures for thissensor?' } %>
  <%= link_to 'Destroy', @sensor, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn" %></td>

</p>
<p>
  <b>Description:</b>
  <%= @sensor.description %>
</p>
<p>
  <b>Id:</b>
  <%= @sensor.id %>
</p>
<p>
  <b>Type:</b>
  <%= @sensor.type %>
</p>

<p>
  <b>Unit:</b>
  <%= @sensor.unit %>
</p>
<p>Numbers of measures:<%= @sensor.measures.count %>
</p>
    <% if @sensor.device %>
	<p>
	<i>Sample API Usage with cURL:
	</i><br/>
	<pre>
curl -i --header "Accept: application/json"  --header "X-ApiKey: <%= @current_user.getApiKey -%>" http://<%= API_ENDPOINT -%>/sensor/<%= @sensor.id -%>
</pre>
Update data on this feed:
  <pre>
curl -i --request POST -H 'Content-Type: application/json;'  --data '[{"sensor_id":"<%= @sensor.id -%>","value":20}]' --header "X-ApiKey: <%= @current_user.getApiKey -%>" http://<%= API_ENDPOINT -%>/device/<%= @sensor.device.id -%>
</pre>
</p>
<% end %>
<div class="row">
  <div class="col-xs-9">
<% if !["String","Boolean","Position"].include? @sensor.type %>
<div id="sensor_chart" style="height: 400px; min-width: 310px"></div>
<script>
function updateGraph(message){
  console.log("update graph");
  console.log(message);
  var toAdd=[new Date(message.timeStamp).getTime(),message.value];
  console.log(chart.series[0]);
  if(chart.series[0].data.length<100){
    chart.series[0].addPoint(toAdd);
  }else{
   chart.series[0].addPoint(toAdd,true,true);
  }
}

render_data=function(data) {
    // Create the chart
     chart=new Highcharts.StockChart(
     {
      chart:{renderTo:"sensor_chart"},
      rangeSelector : {
        selected : 1,
        inputEnabled: $('#sensor_chart').width() > 480
      },
      title : {
        text : '<%= @sensor.name %>'
      },
      series : [{
        name : '<%= @sensor.unit -%>',
        data : data,
        tooltip: {
          valueDecimals: 2
        }
      }]},function(){}
      );
    };

$(function() {

  $.getJSON(
    '<%= raw("http://#{API_ENDPOINT}/sensor/#{@sensor.id}/measures?api_key=#{@current_user.api_key}&callback=?") -%>'
    , render_data);

});
</script>
<% elsif @sensor.type=="Position" %>
    <script type="text/javascript">
    // When the window has finished loading create our google map below
   google.maps.event.addDomListener(window, 'load', init_map);
   var map;
   function init_map() {
    <% if @sensor.last_measure.value %>
     var latLon = new google.maps.LatLng(<%= "#{@sensor.last_measure.value['lat']},#{@sensor.last_measure.value['lon']}" -%>);
     <% else %>
      var latlon = new google.maps.LatLng(48.51,2.21);
     <% end %>

     var mapOptions = {
       center: latLon,
       zoom: 11
     };
     var mapElement = document.getElementById('map-canvas');
     map = new google.maps.Map(mapElement, mapOptions);

     var previousPath = [
<% @sensor.measures.desc(:timeStamp).limit(20).each do |measure| %>
        new google.maps.LatLng(<%= "#{measure.value['lat']},#{measure.value['lon']}" -%>),
<% end %>
    ];

     var polyOptions = {
       path: previousPath,
       strokeColor: '#3333EE',
       strokeOpacity: 0.8,
       //strokeWeight: 3
     };
     poly = new google.maps.Polyline(polyOptions);
     poly.setMap(map);

     marker = new google.maps.Marker({
       position: latLon,
       map: map,
       title:"Updated:<%= @sensor.last_measure.timeStamp -%>"
     });
   }

   function updateGraph(message){
    console.log(message);
     var latLng=new google.maps.LatLng(message.value.lat,message.value.lon);
/*     var marker = new google.maps.Marker({
       position: latLng,
       map: map,
       title:"Updated:"+new Date(message.timeStamp).toLocaleString()
     });*/
     marker.setPosition(latLng);
     marker.setTitle("Updated:"+new Date(message.timeStamp).toLocaleString());
     var path = poly.getPath();
     path.push(latLng);

   }
    </script>
    Map canvas:
    <div id="map-canvas" style="width:100%;height:400px" ></div>

<% else %>
<script>
function updateGraph(message){
  }
</script>
<% end %>
<script>
function updateDatas(message){
      $('#last_table tbody').prepend('<tr><td>'+ (new Date(message.timeStamp)).toLocaleString()+'</td><td>'+message.value+'<%= @sensor.unit %></td></tr>');
      updateGraph(message);
}
</script>
</div>
<div class="col-xs-3">
<H4>Last Measures:</H4>
<table class="table" id="last_table" width=200px>
<% @sensor.measures.desc(:timeStamp).limit(20).each do |measure| %>
<tr>
  <td><%= measure.timeStamp %></td>
  <td><%= "#{measure.value} #{@sensor.unit}"  %></td>
</tr>
<% end %>
<tr><td></td></tr>
</table>
</div>
</div>