config/routes.rb
OpenSensor::Application.routes.draw do
  resources :flows
  resources :flow_power_daily_sum, controller: 'flows', type: 'Flow' 
  resources :flow_avg,             controller: 'flows', type: 'Flow' 


  resources :elements


  resources :actions


  get "welcome/index"

  resources :twitter_credentials do
   collection do
      get 'connect'
      get 'callback'
    end
  end


  resources :element_prototypes


  resources :sensors do
    member do
      delete 'drop'
    end
  end

  resources :triggers


  resources :widgets

  resources :home

  resources :dashboards do
    member do
      post 'positions'
    end
   collection do
      get 'subscribe'
      post 'webhook'
    end
  end
  
  resources :measures


  resources :feeds do
    member do
      get 'graph'
    end
  end

  resources :devices

  authenticated :user do
    root :to => 'users#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users



end

app/models/dashboard.rb
class Dashboard
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :active_channel, type:Boolean ,:default=>false
  field :is_public, type:Boolean, :default=>false
  belongs_to :user
  has_many :widgets
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!,:except=>[:show,:webhook]
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = current_user.dashboards

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dashboards }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = Dashboard.find(params[:id])
    if @dashboard.is_public || authenticate_user! || @dashboard.user==@current_user
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @dashboard }
      end
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(params[:dashboard])
    @dashboard.user=current_user
    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end

  def subscribe
    response.headers['Content-Type'] = 'text/event-stream'
    begin
      loop do
        response.stream.write "data: #{generate_new_values}\n\n" # Add 2 line breaks to delimitate events
        sleep 5.second
      end
    rescue IOError # Raised when browser interrupts the connection
    ensure
      response.stream.close # Prevents stream from being open forever
    end
  end

  # Web hook for Pusher
  def webhook
    puts "webhook"
    Pusher.url = "http://#{PUSHER_KEY}:#{PUSHER_SECRET}@api.pusherapp.com/apps/#{PUSHER_APP}"
    res = Pusher::WebHook.new(request)
    puts request.to_s
    begin
      if res.valid?
        res.events.each do |event|
          elems=event['channel'].split('-')
          active=false
          case event["name"]
          when 'channel_occupied'
            active=true
          when 'channel_vacated'
            active=false
          end
          dbclass=Object.const_get elems[0].capitalize
          db=dbclass.find elems[1]
          db.set(:active_channel,active)
        end
        render text: 'ok'
      else
        render text: 'invalid', status: 401
      end
    rescue Exception => e
      puts "Webhook exception:#{e}"
      render text: 'invalid', status: 401
    end
  end

def positions
  puts "Pos"
  #  binding.pry
  data=request.body.read
  puts ":"+data
  res=JSON.parse data
  puts res
  res.each do | widget_pos|
    widget=Widget.find widget_pos["widget_id"]
    widget.size_x=widget_pos["size_x"]
    widget.size_y=widget_pos["size_y"]
    widget.col=widget_pos["col"]
    widget.row=widget_pos["row"]
    widget.save
  end
  render :json=>{:ok=>1}
end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :is_public %><br />
    <%= f.select(:is_public,options_for_select([["true",true],["false",false]],:default=>@dashboard.is_public)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard ,:class=>"btn"%> |
<%= link_to 'Back', dashboards_path,:class=>"btn" %>

app/views/dashboards/index.html.erb
<h1>Your  dashboards</h1>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>public?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dashboards.each do |dashboard| %>
  <tr>
    <td><%= link_to dashboard.name , dashboard %></td>
    <td><%= dashboard.description %></td>
    <td><%= dashboard.is_public %></td>
    <td><%= link_to 'Show', dashboard %></td>
    <td><%= link_to 'Edit', edit_dashboard_path(dashboard) %></td>
    <td><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dashboard', new_dashboard_path,:class=>"btn btn-primary" %>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path,:class=>"btn" %>

app/views/dashboards/show.html.erb
<script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<link href="/assets/jquery.gridster.css" rel="stylesheet">
<link href="/assets/widget.css" rel="stylesheet">
<script src="/assets/jquery.gridster.js"></script>
<script src="/assets/raphael-min.js"></script>
<script src="/assets/justgage.1.0.1.min.js"></script>
<script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLFKOt7Y2ggj_6P_lNH8BOp_WmZ84K1Jc&sensor=SET_TO_TRUE_OR_FALSE" >
</script>

<script type="text/javascript">
Highcharts.setOptions({ global: {timezoneOffset:(new Date()).getTimezoneOffset() ,useUTC: true}});

var gridster;
var dashboard_id='<%= @dashboard.id -%>';
$(function(){ //DOM Ready
 
    gridster=$(".gridster ul").gridster({
        widget_margins: [5, 5],
        widget_base_dimensions: [140, 140],
        draggable:{stop: function(e, ui, $widget) {console.log("end drag");gridster_save(this);}},
    	resize:{enabled: true,  stop: function(e, ui, $widget) {
    		console.log("Resize");
	    	$.each(Widget.widgets,function(index,widget){
    			if(widget.on_resize)widget.on_resize(widget,$widget);
	    	});
    		gridster_save(this);
        }}
    });
//    gridster_elem=gridster.data('gridster');

    gridster_save=function(data){

    	var newPos=data.serialize();
    	var i=0;
    	$.each(Widget.widgets,function(index,widget){
    		newPos[i++].widget_id=index;
    	});
    	// Save new positins
    	console.log(newPos);

    	$.post("/dashboards/"+dashboard_id+"/positions",
	    	JSON.stringify(newPos),
    		function(data) {console.log("Pos Saved...");}
    	);

    }
    
    gridster.on_stop_drag=function(event,ui){
    	console.log("stop drag");
//    	this.save();
    }
 	Widget.init_all();
});
// Pusher
Pusher.log = function(message) {
	if (window.console && window.console.log) {
		        window.console.log(message);
	}
};
<% use_presence=false %>
var prefix="<%= if use_presence then "presence-" else "" end %>";
var pusher = new Pusher(prefix+'<%= PUSHER_KEY -%>', { authEndpoint: '/dashboard/auth' });
var channel = pusher.subscribe('<%= "dashboard-#{@dashboard.id}" -%>');
channel.bind('update', function(data) {
	console.log(data);
	updateDashboard(data);
});
function updateDashboard(message){
	console.log(message);
	$.each(message,function(index,val){
		console.log("updating:"+val._id);
		var widget=Widget.widgets[val._id];
		if(widget && widget.on_update)widget.on_update(val);
	});
}

function Widget (widget_id,options) {
    this._id = widget_id;
    console.log(options);
    var self=this;
    if(options){
        $.each(options,function(k,v){
    	    self[k]=v;
        })
        ;
	}
}
Widget.widgets={};
Widget.prototype.getInfo = function() {
    return this.widget_id;
};
Widget.addWidget=function(widget_id,options)
{
	this.widgets[widget_id]=new Widget(widget_id,options);
}
Widget.init_all=function(){
	$.each(Widget.widgets,function(index,widget){
		if(widget.on_init)widget.on_init();
	});
}
</script>
 
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-10">
	<h3><%= @dashboard.name %></H3>
	<%= @dashboard.description %>
  </div>
  <div class="col-md-2">
<% if @dashboard.user==@current_user %>
	<%= link_to "Add widget",new_widget_path(:dashboard=>@dashboard.id),:class=>"btn btn-primary" %>
	<%= link_to raw("<span class='glyphicon glyphicon-cog'	></span>"), edit_dashboard_path(@dashboard),:class=>"btn" %> 
<% end %>
  </div>
</div>
<div class="gridster">
    <ul>
    	<%= render @dashboard.widgets %>
    </ul>
</div>
<br>
<br/>